name: CI/CD Pipeline

on:
  push:
    branches:
      - developer_2  # Branche Ã  surveiller

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: ğŸ§¾ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ‹ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ“¦ Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: ğŸ”§ Build containers
        run: docker-compose -f docker-compose.yml build

      - name: ğŸš€ Start containers
        run: docker-compose -f docker-compose.yml up -d

      - name: â± Wait for backend to be ready
        run: sleep 15

      - name: ğŸ” Check backend API response
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://moustassweb.com:3000| grep 200

      - name: ğŸ§¹ Stop and clean containers
        run: docker-compose -f docker-compose.yml down
